<a href="https://colab.research.google.com/github/gurnursingh05/contoso/blob/main/TimeandDate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [29]:
%%sql
SELECT
  TO_CHAR(orderdate, 'YYYY-MM') as order_month,
  SUM(s.quantity * s.netprice * s.exchangerate) as revenue,
  COUNT(DISTINCT customerkey) as unique_customers
FROM
  sales s
GROUP BY
  order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_month    revenue  unique_customers
0       2015-01  384092.66               200
1       2015-02  706374.12               291
2       2015-03  332961.59               139
3       2015-04  160767.00                78
4       2015-05  548632.63               236
..          ...        ...               ...
107     2023-12 2928550.93              1484
108     2024-01 2677498.55              1340
109     2024-02 3542322.55              1718
110     2024-03 1692854.89               877
111     2024-04  483851.39               246

[112 rows x 3 columns]

In [30]:
%%sql
SELECT
  DATE_PART('year', orderdate) as order_year,
  DATE_PART('month', orderdate) as order_month,
  DATE_PART('day', orderdate) as order_day
FROM
  sales
ORDER BY
  RANDOM()
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   order_year  order_month  order_day
0     2018.00        12.00       1.00
1     2017.00         5.00      27.00
2     2018.00         9.00      17.00
3     2024.00         2.00      28.00
4     2019.00         5.00       7.00
5     2019.00         8.00      12.00
6     2022.00         2.00      26.00
7     2023.00         8.00      28.00
8     2019.00        12.00      29.00
9     2020.00         2.00      27.00

In [31]:
%%sql
SELECT
  EXTRACT(YEAR FROM orderdate) as order_year,
  EXTRACT(MONTH FROM orderdate) as order_month,
  EXTRACT(DAY FROM orderdate) as order_day
FROM
  sales
ORDER BY
  RANDOM()
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  order_year order_month order_day
0       2018          11        20
1       2024           2        27
2       2020          11         3
3       2016           9        28
4       2024           2        21
5       2022           8        30
6       2021           9        18
7       2023           5         4
8       2023           9         4
9       2024           1        20